

WITH RAW_COMPANY_LOCATION AS (
    SELECT * FROM {{ source('airbyte_database', 'company_location') }}
)

SELECT 
    _AIRBYTE_RAW_COMPANY_HASHID AS COMPANY_ID,
    CITY AS COMPANY_CITY,
    STATE AS COMPANY_STATE,
    ADDRESS AS COMPANY_ADDRESS,
    COUNTRY AS COMPANY_COUNTRY,
    POSTALCODE AS COMPANY_POSTALCODE
FROM
    RAW_COMPANY_LOCATION