

WITH RAW_COMPANY_SOCIALMEDIA AS (
    SELECT * FROM {{ source('airbyte_database', 'company_social_media') }}
)

SELECT 
    _AIRBYTE_SOCIALMEDIA_HASHID AS HASHID_SOCIALMEDIA,
    _AIRBYTE_RAW_COMPANY_HASHID AS COMPANY_ID,
    TWITTER AS COMPANY_TWITTER,
    FACEBOOK AS COMPANY_FACEBOOK,
    LINKEDIN AS COMPANY_LINKEDIN
FROM
    RAW_COMPANY_SOCIALMEDIA