
WITH RAW_COMPANY AS (
    SELECT * FROM {{ source('airbyte_database', 'company') }}
)

SELECT 
    _AIRBYTE_RAW_COMPANY_HASHID AS COMPANY_ID,
    NAME AS COMPANY_NAME,
    REVENUE AS COMPANY_REVENUE,
    WEBSITE AS COMPANY_WEBSITE,
    INDUSTRY AS COMPANY_INDUSTRY,
    DESCRIPTION AS COMPANY_DESCRIPTION,
    FOUNDEDYEAR AS COMPANY_FOUNDEDYEAR,
    EMPLOYEESCOUNT AS COMPANY_EMPLOYEE_COUNT,
    SPECIALTIES AS COMPANY_SPECIALTY,
    LOGOURL AS COMPANY_LOGO_URL
FROM
    RAW_COMPANY