{{
    config(
        materialized = 'view'
    )
}}

WITH SRC_EDUCATION AS (
    SELECT * FROM {{ ref('src_education') }}
)

SELECT PROFILE_ID,
CAST(EDUCATION_STARTDATE AS TIMESTAMP) AS EDU_START,
CAST(EDUCATION_ENDDATE AS TIMESTAMP) AS EDU_END,
DATEDIFF(MONTH, EDU_START, EDU_END) AS MONTHS,
SCHOOL,
DEGREE,
MAJOR

FROM SRC_EDUCATION

WHERE EDUCATION_DELETED = FALSE