
WITH RAW_PROFILE_EDUCATION AS (
    SELECT * FROM {{ source('airbyte_database', 'profile_education') }}
)

SELECT 
    _AIRBYTE_EDUCATION_HASHID AS HASHID_EDUCATION,
    _AIRBYTE_RAW_PROFILE_HASHID AS PROFILE_ID,
    STARTDATE AS EDUCATION_STARTDATE,
    ENDDATE AS EDUCATION_ENDDATE,
    SCHOOL,
    DEGREE,
    MAJOR,
    DELETED AS EDUCATION_DELETED
FROM
    RAW_PROFILE_EDUCATION