

WITH RAW_PROFILE AS (
    SELECT * FROM {{ source('airbyte_database', 'profile') }}
)

SELECT 
    _AIRBYTE_RAW_PROFILE_HASHID AS PROFILE_ID,
    NAME AS PROFILE_NAME,
    SUMMARY AS PROFILE_SUMMARY,
    HEADLINE AS PROFILE_HEADLINE,
    INDUSTRY AS PROFILE_INDUSTRY
FROM
    RAW_PROFILE