
WITH RAW_PROFILE_SKILLS AS (
    SELECT * FROM {{ source('airbyte_database', 'profile_skills') }}
)

SELECT 
    _AIRBYTE_SKILLS_HASHID AS HASHID_SKILLS,
    _AIRBYTE_RAW_PROFILE_HASHID AS PROFILE_ID,
    NAME AS SKILL_TYPE,
    LEVEL AS SKILL_LEVEL
FROM
    RAW_PROFILE_SKILLS