
WITH RAW_PROFILE_LOCATION AS (
    SELECT * FROM {{ source('airbyte_database', 'profile_location') }}
)

SELECT 
    _AIRBYTE_RAW_PROFILE_HASHID AS PROFILE_ID,
    CITY AS PROFILE_CITY,
    STATE AS PROFILE_STATE,
    COUNTRY AS PROFILE_COUNTRY
FROM
    RAW_PROFILE_LOCATION